import React from 'react'
import './Home.scss'
import Featured from '../../components/featured/Featured'

const Home = () => {
  return (
    <div className='home'>
      <Featured/>
      
      <br />
        <br /><br /><br /><br /><br /><br />
        <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, distinctio? Delectus, accusantium voluptates. Doloremque, praesentium. In incidunt libero ratione repellendus, architecto quo dolorem aut voluptate modi pariatur eligendi, iste maiores?</h1>
        <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, distinctio? Delectus, accusantium voluptates. Doloremque, praesentium. In incidunt libero ratione repellendus, architecto quo dolorem aut voluptate modi pariatur eligendi, iste maiores?</h1>
        <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, distinctio? Delectus, accusantium voluptates. Doloremque, praesentium. In incidunt libero ratione repellendus, architecto quo dolorem aut voluptate modi pariatur eligendi, iste maiores?</h1>
        <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, distinctio? Delectus, accusantium voluptates. Doloremque, praesentium. In incidunt libero ratione repellendus, architecto quo dolorem aut voluptate modi pariatur eligendi, iste maiores?</h1>
        <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, distinctio? Delectus, accusantium voluptates. Doloremque, praesentium. In incidunt libero ratione repellendus, architecto quo dolorem aut voluptate modi pariatur eligendi, iste maiores?</h1>
        <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, distinctio? Delectus, accusantium voluptates. Doloremque, praesentium. In incidunt libero ratione repellendus, architecto quo dolorem aut voluptate modi pariatur eligendi, iste maiores?</h1>
        <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, distinctio? Delectus, accusantium voluptates. Doloremque, praesentium. In incidunt libero ratione repellendus, architecto quo dolorem aut voluptate modi pariatur eligendi, iste maiores?</h1>
        <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, distinctio? Delectus, accusantium voluptates. Doloremque, praesentium. In incidunt libero ratione repellendus, architecto quo dolorem aut voluptate modi pariatur eligendi, iste maiores?</h1>
        <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, distinctio? Delectus, accusantium voluptates. Doloremque, praesentium. In incidunt libero ratione repellendus, architecto quo dolorem aut voluptate modi pariatur eligendi, iste maiores?</h1>
        <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, distinctio? Delectus, accusantium voluptates. Doloremque, praesentium. In incidunt libero ratione repellendus, architecto quo dolorem aut voluptate modi pariatur eligendi, iste maiores?</h1>
        <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, distinctio? Delectus, accusantium voluptates. Doloremque, praesentium. In incidunt libero ratione repellendus, architecto quo dolorem aut voluptate modi pariatur eligendi, iste maiores?</h1>
        <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, distinctio? Delectus, accusantium voluptates. Doloremque, praesentium. In incidunt libero ratione repellendus, architecto quo dolorem aut voluptate modi pariatur eligendi, iste maiores?</h1>
        <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, distinctio? Delectus, accusantium voluptates. Doloremque, praesentium. In incidunt libero ratione repellendus, architecto quo dolorem aut voluptate modi pariatur eligendi, iste maiores?</h1>
        <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, distinctio? Delectus, accusantium voluptates. Doloremque, praesentium. In incidunt libero ratione repellendus, architecto quo dolorem aut voluptate modi pariatur eligendi, iste maiores?</h1>
        <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, distinctio? Delectus, accusantium voluptates. Doloremque, praesentium. In incidunt libero ratione repellendus, architecto quo dolorem aut voluptate modi pariatur eligendi, iste maiores?</h1>
        <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, distinctio? Delectus, accusantium voluptates. Doloremque, praesentium. In incidunt libero ratione repellendus, architecto quo dolorem aut voluptate modi pariatur eligendi, iste maiores?</h1>
        <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, distinctio? Delectus, accusantium voluptates. Doloremque, praesentium. In incidunt libero ratione repellendus, architecto quo dolorem aut voluptate modi pariatur eligendi, iste maiores?</h1>
        <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, distinctio? Delectus, accusantium voluptates. Doloremque, praesentium. In incidunt libero ratione repellendus, architecto quo dolorem aut voluptate modi pariatur eligendi, iste maiores?</h1>
        <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, distinctio? Delectus, accusantium voluptates. Doloremque, praesentium. In incidunt libero ratione repellendus, architecto quo dolorem aut voluptate modi pariatur eligendi, iste maiores?</h1>
        <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, distinctio? Delectus, accusantium voluptates. Doloremque, praesentium. In incidunt libero ratione repellendus, architecto quo dolorem aut voluptate modi pariatur eligendi, iste maiores?</h1>
        <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, distinctio? Delectus, accusantium voluptates. Doloremque, praesentium. In incidunt libero ratione repellendus, architecto quo dolorem aut voluptate modi pariatur eligendi, iste maiores?</h1>
        <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, distinctio? Delectus, accusantium voluptates. Doloremque, praesentium. In incidunt libero ratione repellendus, architecto quo dolorem aut voluptate modi pariatur eligendi, iste maiores?</h1>
        <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, distinctio? Delectus, accusantium voluptates. Doloremque, praesentium. In incidunt libero ratione repellendus, architecto quo dolorem aut voluptate modi pariatur eligendi, iste maiores?</h1>
        <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, distinctio? Delectus, accusantium voluptates. Doloremque, praesentium. In incidunt libero ratione repellendus, architecto quo dolorem aut voluptate modi pariatur eligendi, iste maiores?</h1>
        <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, distinctio? Delectus, accusantium voluptates. Doloremque, praesentium. In incidunt libero ratione repellendus, architecto quo dolorem aut voluptate modi pariatur eligendi, iste maiores?</h1>
        <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, distinctio? Delectus, accusantium voluptates. Doloremque, praesentium. In incidunt libero ratione repellendus, architecto quo dolorem aut voluptate modi pariatur eligendi, iste maiores?</h1>
        <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, distinctio? Delectus, accusantium voluptates. Doloremque, praesentium. In incidunt libero ratione repellendus, architecto quo dolorem aut voluptate modi pariatur eligendi, iste maiores?</h1>
        <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, distinctio? Delectus, accusantium voluptates. Doloremque, praesentium. In incidunt libero ratione repellendus, architecto quo dolorem aut voluptate modi pariatur eligendi, iste maiores?</h1>
        <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, distinctio? Delectus, accusantium voluptates. Doloremque, praesentium. In incidunt libero ratione repellendus, architecto quo dolorem aut voluptate modi pariatur eligendi, iste maiores?</h1>
        <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, distinctio? Delectus, accusantium voluptates. Doloremque, praesentium. In incidunt libero ratione repellendus, architecto quo dolorem aut voluptate modi pariatur eligendi, iste maiores?</h1>
        <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, distinctio? Delectus, accusantium voluptates. Doloremque, praesentium. In incidunt libero ratione repellendus, architecto quo dolorem aut voluptate modi pariatur eligendi, iste maiores?</h1>
        <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, distinctio? Delectus, accusantium voluptates. Doloremque, praesentium. In incidunt libero ratione repellendus, architecto quo dolorem aut voluptate modi pariatur eligendi, iste maiores?</h1>
        <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, distinctio? Delectus, accusantium voluptates. Doloremque, praesentium. In incidunt libero ratione repellendus, architecto quo dolorem aut voluptate modi pariatur eligendi, iste maiores?</h1>
        <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, distinctio? Delectus, accusantium voluptates. Doloremque, praesentium. In incidunt libero ratione repellendus, architecto quo dolorem aut voluptate modi pariatur eligendi, iste maiores?</h1>
        <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, distinctio? Delectus, accusantium voluptates. Doloremque, praesentium. In incidunt libero ratione repellendus, architecto quo dolorem aut voluptate modi pariatur eligendi, iste maiores?</h1>
        <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, distinctio? Delectus, accusantium voluptates. Doloremque, praesentium. In incidunt libero ratione repellendus, architecto quo dolorem aut voluptate modi pariatur eligendi, iste maiores?</h1>
        <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, distinctio? Delectus, accusantium voluptates. Doloremque, praesentium. In incidunt libero ratione repellendus, architecto quo dolorem aut voluptate modi pariatur eligendi, iste maiores?</h1>
        <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, distinctio? Delectus, accusantium voluptates. Doloremque, praesentium. In incidunt libero ratione repellendus, architecto quo dolorem aut voluptate modi pariatur eligendi, iste maiores?</h1>
        <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, distinctio? Delectus, accusantium voluptates. Doloremque, praesentium. In incidunt libero ratione repellendus, architecto quo dolorem aut voluptate modi pariatur eligendi, iste maiores?</h1>
        <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, distinctio? Delectus, accusantium voluptates. Doloremque, praesentium. In incidunt libero ratione repellendus, architecto quo dolorem aut voluptate modi pariatur eligendi, iste maiores?</h1>
        <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, distinctio? Delectus, accusantium voluptates. Doloremque, praesentium. In incidunt libero ratione repellendus, architecto quo dolorem aut voluptate modi pariatur eligendi, iste maiores?</h1>
        <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, distinctio? Delectus, accusantium voluptates. Doloremque, praesentium. In incidunt libero ratione repellendus, architecto quo dolorem aut voluptate modi pariatur eligendi, iste maiores?</h1>
        <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, distinctio? Delectus, accusantium voluptates. Doloremque, praesentium. In incidunt libero ratione repellendus, architecto quo dolorem aut voluptate modi pariatur eligendi, iste maiores?</h1>
        <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, distinctio? Delectus, accusantium voluptates. Doloremque, praesentium. In incidunt libero ratione repellendus, architecto quo dolorem aut voluptate modi pariatur eligendi, iste maiores?</h1>
        <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, distinctio? Delectus, accusantium voluptates. Doloremque, praesentium. In incidunt libero ratione repellendus, architecto quo dolorem aut voluptate modi pariatur eligendi, iste maiores?</h1>
        <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, distinctio? Delectus, accusantium voluptates. Doloremque, praesentium. In incidunt libero ratione repellendus, architecto quo dolorem aut voluptate modi pariatur eligendi, iste maiores?</h1>
        <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, distinctio? Delectus, accusantium voluptates. Doloremque, praesentium. In incidunt libero ratione repellendus, architecto quo dolorem aut voluptate modi pariatur eligendi, iste maiores?</h1>
        <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, distinctio? Delectus, accusantium voluptates. Doloremque, praesentium. In incidunt libero ratione repellendus, architecto quo dolorem aut voluptate modi pariatur eligendi, iste maiores?</h1>
        <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, distinctio? Delectus, accusantium voluptates. Doloremque, praesentium. In incidunt libero ratione repellendus, architecto quo dolorem aut voluptate modi pariatur eligendi, iste maiores?</h1>

    </div>
  )
}

export default Home